export const READING_PART_2 = [
  {
    id: 1,
    examId: 1,
    parentId: null,
    content: `<div><p><strong>FLUORIDATION OF PUBLIC WATER SUPPLIES</strong></p>

      <p>Water fluoridation is the process of releasing small amounts of fluoride into the public water supply as a way to reduce dental health problems. The process of reducing tooth decay through fluoridation is clearly understood, and research confirms water fluoridation's effect on limiting instances of tooth decay. Nevertheless, fluoride is not harmless in all quantities. At levels moderately above those desired, it can result in something known as fluorosis, and at very high levels acute fluoride poisoning can occur.</p>

      <p>Fluoride's function is to intervene in the demineralisation mechanism of tooth decay. Demineralisation is a process that begins when sugary carbohydrates are eaten, and organic acids are subsequently generated by bacteria within the dental plaque. When a certain level of acidity is produced (pH in the oral cavity dips below 5.5), the acids waste away the main component of tooth enamel, a substance known as carbonated hydroxyapatite. If this erosion persists for months and years without adequate remineralisation, then tooth decay occurs, and dental cavities form.</p>

      <p>Fluoride can greatly assist the mouth with the remineralisation of decaying enamel. Fluoridation creates fluoride ions in saliva that can restore some of the lost mineral content from enamel after sugary acids have left the oral cavity. When these ions exist in plaque fluid alongside dissolved carbonated hydroxyapatite, and the pH is higher than 4.5, a fluorapatite veneer covers the dental enamel. This veneer has the benefit of being more acid-resistant than the tooth's hydroxyapatite, and is formed more quickly than by the natural remineralisation mechanism. Blood plasma transports any fluoride that has been ingested to calcium-rich areas such as the teeth, supporting dental infrastructure from the inside as well.</p>

      <p>The U.S. Center for Disease Control has listed fluoridation of the water supply as one of the greatest public health achievements of the 20th century. While tooth decay is rarely a threat to mortality, it is one of the most prevalent chronic diseases globally and affects 60-90 percent of children across industrialised countries. Research suggests that the presence of fluoride in saliva at all times (but in small quantities) is the single most effective preventative measure of tooth decay. Water fluoridation is perfectly geared towards helping to ensure this. Drinking water is the largest source of fluoride for people globally, and evidence demonstrates its efficacy in reducing cavities, particularly among poorer households without regular access to dentists.</p>

      <p>Although not considered to be an essential ingredient (a substance necessary to perpetuate human life and biological development), fluoride can be considered a nutrient that counteracts harmful processes from lifestyle or environmental factors. Nevertheless, in doses higher than those desirable, a side effect known as dental fluorosis can occur. Its primary symptoms—pale streaking across the incisors—are considered a cosmetic problem for many people. The key risk period for developing fluorosis is ages one to four, with any likelihood of getting it having depleted by age eight. Young children are therefore encouraged to have their fluoride ingestion monitored—reduction of fluoride in infant formula and children's toothpaste has assisted this process.</p>

      <p>Far more serious than mild dental fluorosis, however, yet much rarer, is a condition known as acute fluoride poisoning. This does not happen very often, as it is unlikely that most people would ever come into contact with large amounts of fluoride. When it does happen, it is typically a consequence of water technicians accidentally allowing excess amounts of fluoride into the system, which is then ingested by an unsuspecting public. In one of the worst instances of fluoride poisoning, 262 people became ill and one person died in Alaska in 1992. During 2010 in Asheboro, North Carolina, 60 gallons of fluoride were released into the water supply in 90 minutes; this amount was intended for release over a 24-hour period. These incidents highlight the importance of careful monitoring to ensure public safety.</p>

      <p>Not everyone supports water fluoridation. Paul Connett, a chemistry professor from St. Lawrence University, has listed many reasons to oppose the practice. Firstly, he suggests, studies that have tracked the effects of discontinuing fluoridation in communities from Canada, Germany, Cuba and Finland have found that instances of dental decay actually dropped considerably as a result of halting the practice. Secondly, Connett finds that once water supplies are fluoridated it is impossible to control individual doses. This is because some people (manual labourers, athletes, diabetics, and people with kidney disease) drink more water than others, and we also receive fluoride from sources other than tap water.</p>

      <p>Connett also expresses concern for purely ethical reasons, believing fluoridation to contradict the medical ethic of informed consent. Informed consent requires patients to be fully informed about medical operations before consenting to them—fluoridation evades this process. Finally, Connett points to the World Health Organisation's acknowledgement that fluoride's benefits are primarily achieved topically, that is, applied to the surface of teeth, rather than systemically (ingested).</p></div>`,
    document: {
      type: 'IMAGE',
      url: 'https://example.com/image1.jpg',
      metadata: {}
    },
    type: 'READING',
    order: 1,
    answers: [],
    createdBy: { id: 1, name: 'Admin' },
    updatedBy: { id: 1, name: 'Admin' },
    updatedAt: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z'
  },

  ...Array.from({ length: 13 }, (_, i) => ({
    id: i + 1,
    examId: 1,
    parentId: 1,
    content: `Question content for Reading Part 1 - Question ${i + 1}`,
    document: null,
    type: 'READING',
    order: i + 1,
    answers: [
      {
        id: i * 4 + 1,
        questionId: i + 1,
        isCorrect: i % 2 === 0,
        content: 'Answer A',
        order: 1,
        updatedBy: { id: 1, name: 'Admin' },
        updatedAt: '2024-01-01T00:00:00Z',
        createdAt: '2024-01-01T00:00:00Z',
      },
      {
        id: i * 4 + 2,
        questionId: i + 1,
        isCorrect: i % 2 !== 0,
        content: 'Answer B',
        order: 2,
        updatedBy: { id: 1, name: 'Admin' },
        updatedAt: '2024-01-01T00:00:00Z',
        createdAt: '2024-01-01T00:00:00Z',
      },
      {
        id: i * 4 + 3,
        questionId: i + 1,
        isCorrect: false,
        content: 'Answer C',
        order: 3,
        updatedBy: { id: 1, name: 'Admin' },
        updatedAt: '2024-01-01T00:00:00Z',
        createdAt: '2024-01-01T00:00:00Z',
      },
      {
        id: i * 4 + 4,
        questionId: i + 1,
        isCorrect: false,
        content: 'Answer D',
        order: 4,
        updatedBy: { id: 1, name: 'Admin' },
        updatedAt: '2024-01-01T00:00:00Z',
        createdAt: '2024-01-01T00:00:00Z',
      },
    ],
    createdBy: { id: 1, name: 'Admin' },
    updatedBy: { id: 1, name: 'Admin' },
    updatedAt: '2024-01-01T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
  })),
]